#!/bin/bash

source .env

BUILD_TYPE="${BUILD_TYPE:-Release}"
BUILD_DIR="${BUILD_DIR:-.build_release}"

cmake -G Ninja -S . -B $BUILD_DIR \
  -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
  -DNPRPC_BUILD_TESTS=ON \
  -DNPRPC_BUILD_TOOLS=ON \
  -DNPRPC_ENABLE_QUIC=ON \
  -DNPRPC_ENABLE_HTTP3=ON \
  -DNPRPC_ENABLE_SSR=ON \
  -DNPRPC_BUILD_DEV_DOCKER=ON \
  -DNPRPC_BUILD_EXAMPLES=ON \
  -DNPRPC_BUILD_NODE_ADDON=ON
