// Generated by npidl compiler
// DO NOT EDIT - all changes will be lost

import NPRPC

public typealias binary = [UInt8]
public enum PresenceEventKind: Int32, Codable, Sendable {
  case joined
  case left
  case typing
}

public struct AuthorPreview: Codable, Sendable {
  public var id: UInt64 = 0
  public var slug: String = ""
  public var name: String = ""
  public var bio: String = ""
  public var avatar_url: String = ""

  public init() {}

  public init(id: UInt64, slug: String, name: String, bio: String, avatar_url: String)   {
    self.id = id
    self.slug = slug
    self.name = name
    self.bio = bio
    self.avatar_url = avatar_url
  }
}


// MARK: - Marshal AuthorPreview
public func marshal_AuthorPreview(buffer: FlatBuffer, offset: Int, data: AuthorPreview) {
  guard let buf = buffer.data else { return }
  buf.storeBytes(of: data.id, toByteOffset: offset + 0, as: UInt64.self)
  NPRPC.marshal_string(buffer: buffer, offset: offset + 8, string: data.slug)
  NPRPC.marshal_string(buffer: buffer, offset: offset + 16, string: data.name)
  NPRPC.marshal_string(buffer: buffer, offset: offset + 24, string: data.bio)
  NPRPC.marshal_string(buffer: buffer, offset: offset + 32, string: data.avatar_url)
}

// MARK: - Unmarshal AuthorPreview
public func unmarshal_AuthorPreview(buffer: UnsafeRawPointer, offset: Int) -> AuthorPreview {
  var result = AuthorPreview()
  result.id = buffer.load(fromByteOffset: offset + 0, as: UInt64.self)
  result.slug = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 8)
  result.name = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 16)
  result.bio = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 24)
  result.avatar_url = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 32)
  return result
}

public struct PostPreview: Codable, Sendable {
  public var id: UInt64 = 0
  public var slug: String = ""
  public var title: String = ""
  public var excerpt: String = ""
  public var published_at: String = ""
  public var cover_url: String? = nil
  public var author: AuthorPreview = AuthorPreview()

  public init() {}

  public init(id: UInt64, slug: String, title: String, excerpt: String, published_at: String, cover_url: String?, author: AuthorPreview)   {
    self.id = id
    self.slug = slug
    self.title = title
    self.excerpt = excerpt
    self.published_at = published_at
    self.cover_url = cover_url
    self.author = author
  }
}


// MARK: - Marshal PostPreview
public func marshal_PostPreview(buffer: FlatBuffer, offset: Int, data: PostPreview) {
  guard let buf = buffer.data else { return }
  buf.storeBytes(of: data.id, toByteOffset: offset + 0, as: UInt64.self)
  NPRPC.marshal_string(buffer: buffer, offset: offset + 8, string: data.slug)
  NPRPC.marshal_string(buffer: buffer, offset: offset + 16, string: data.title)
  NPRPC.marshal_string(buffer: buffer, offset: offset + 24, string: data.excerpt)
  NPRPC.marshal_string(buffer: buffer, offset: offset + 32, string: data.published_at)
  if let value = data.cover_url {
    NPRPC.marshal_optional_struct(buffer: buffer, offset: offset + 40, value: value) { buf, off in
      NPRPC.marshal_string(buffer: buf, offset: off, string: value)
    }
  } else {
    buf.storeBytes(of: UInt32(0), toByteOffset: offset + 40, as: UInt32.self)
  }
  marshal_AuthorPreview(buffer: buffer, offset: offset + 48, data: data.author)
}

// MARK: - Unmarshal PostPreview
public func unmarshal_PostPreview(buffer: UnsafeRawPointer, offset: Int) -> PostPreview {
  var result = PostPreview()
  result.id = buffer.load(fromByteOffset: offset + 0, as: UInt64.self)
  result.slug = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 8)
  result.title = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 16)
  result.excerpt = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 24)
  result.published_at = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 32)
  if buffer.load(fromByteOffset: offset + 40, as: UInt32.self) != 0 {
    result.cover_url = NPRPC.unmarshal_optional_struct(buffer: buffer, offset: offset + 40) { buf, off in
      NPRPC.unmarshal_string(buffer: buf, offset: off)
    }
  } else {
    result.cover_url = nil
  }
  result.author = unmarshal_AuthorPreview(buffer: buffer, offset: offset + 48)
  return result
}

public struct PostPage: Codable, Sendable {
  public var page: UInt32 = 0
  public var page_size: UInt32 = 0
  public var total_posts: UInt32 = 0
  public var posts: [PostPreview] = []

  public init() {}

  public init(page: UInt32, page_size: UInt32, total_posts: UInt32, posts: [PostPreview])   {
    self.page = page
    self.page_size = page_size
    self.total_posts = total_posts
    self.posts = posts
  }
}


// MARK: - Marshal PostPage
public func marshal_PostPage(buffer: FlatBuffer, offset: Int, data: PostPage) {
  guard let buf = buffer.data else { return }
  buf.storeBytes(of: data.page, toByteOffset: offset + 0, as: UInt32.self)
  buf.storeBytes(of: data.page_size, toByteOffset: offset + 4, as: UInt32.self)
  buf.storeBytes(of: data.total_posts, toByteOffset: offset + 8, as: UInt32.self)
  NPRPC.marshal_struct_vector(buffer: buffer, offset: offset + 12, vector: data.posts, elementSize: 88, elementAlignment: 8) { buf, off, elem in
    marshal_PostPreview(buffer: buf, offset: off, data: elem)
  }
}

// MARK: - Unmarshal PostPage
public func unmarshal_PostPage(buffer: UnsafeRawPointer, offset: Int) -> PostPage {
  var result = PostPage()
  result.page = buffer.load(fromByteOffset: offset + 0, as: UInt32.self)
  result.page_size = buffer.load(fromByteOffset: offset + 4, as: UInt32.self)
  result.total_posts = buffer.load(fromByteOffset: offset + 8, as: UInt32.self)
  result.posts = NPRPC.unmarshal_struct_vector(buffer: buffer, offset: offset + 12, elementSize: 88) { buf, off in
    unmarshal_PostPreview(buffer: buf, offset: off)
  }
  return result
}

public struct PostDetail: Codable, Sendable {
  public var id: UInt64 = 0
  public var slug: String = ""
  public var title: String = ""
  public var summary: String = ""
  public var body_html: String = ""
  public var published_at: String = ""
  public var author: AuthorPreview = AuthorPreview()
  public var tags: [String] = []

  public init() {}

  public init(id: UInt64, slug: String, title: String, summary: String, body_html: String, published_at: String, author: AuthorPreview, tags: [String])   {
    self.id = id
    self.slug = slug
    self.title = title
    self.summary = summary
    self.body_html = body_html
    self.published_at = published_at
    self.author = author
    self.tags = tags
  }
}


// MARK: - Marshal PostDetail
public func marshal_PostDetail(buffer: FlatBuffer, offset: Int, data: PostDetail) {
  guard let buf = buffer.data else { return }
  buf.storeBytes(of: data.id, toByteOffset: offset + 0, as: UInt64.self)
  NPRPC.marshal_string(buffer: buffer, offset: offset + 8, string: data.slug)
  NPRPC.marshal_string(buffer: buffer, offset: offset + 16, string: data.title)
  NPRPC.marshal_string(buffer: buffer, offset: offset + 24, string: data.summary)
  NPRPC.marshal_string(buffer: buffer, offset: offset + 32, string: data.body_html)
  NPRPC.marshal_string(buffer: buffer, offset: offset + 40, string: data.published_at)
  marshal_AuthorPreview(buffer: buffer, offset: offset + 48, data: data.author)
  NPRPC.marshal_string_vector(buffer: buffer, offset: offset + 88, vector: data.tags)
}

// MARK: - Unmarshal PostDetail
public func unmarshal_PostDetail(buffer: UnsafeRawPointer, offset: Int) -> PostDetail {
  var result = PostDetail()
  result.id = buffer.load(fromByteOffset: offset + 0, as: UInt64.self)
  result.slug = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 8)
  result.title = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 16)
  result.summary = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 24)
  result.body_html = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 32)
  result.published_at = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 40)
  result.author = unmarshal_AuthorPreview(buffer: buffer, offset: offset + 48)
  result.tags = NPRPC.unmarshal_string_vector(buffer: buffer, offset: offset + 88)
  return result
}

public struct Comment: Codable, Sendable {
  public var id: UInt64 = 0
  public var author_name: String = ""
  public var body: String = ""
  public var created_at: String = ""

  public init() {}

  public init(id: UInt64, author_name: String, body: String, created_at: String)   {
    self.id = id
    self.author_name = author_name
    self.body = body
    self.created_at = created_at
  }
}


// MARK: - Marshal Comment
public func marshal_Comment(buffer: FlatBuffer, offset: Int, data: Comment) {
  guard let buf = buffer.data else { return }
  buf.storeBytes(of: data.id, toByteOffset: offset + 0, as: UInt64.self)
  NPRPC.marshal_string(buffer: buffer, offset: offset + 8, string: data.author_name)
  NPRPC.marshal_string(buffer: buffer, offset: offset + 16, string: data.body)
  NPRPC.marshal_string(buffer: buffer, offset: offset + 24, string: data.created_at)
}

// MARK: - Unmarshal Comment
public func unmarshal_Comment(buffer: UnsafeRawPointer, offset: Int) -> Comment {
  var result = Comment()
  result.id = buffer.load(fromByteOffset: offset + 0, as: UInt64.self)
  result.author_name = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 8)
  result.body = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 16)
  result.created_at = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 24)
  return result
}

public struct ChatEnvelope: Codable, Sendable {
  public var author: String = ""
  public var body: String = ""
  public var created_at: String = ""

  public init() {}

  public init(author: String, body: String, created_at: String)   {
    self.author = author
    self.body = body
    self.created_at = created_at
  }
}


// MARK: - Marshal ChatEnvelope
public func marshal_ChatEnvelope(buffer: FlatBuffer, offset: Int, data: ChatEnvelope) {
  NPRPC.marshal_string(buffer: buffer, offset: offset + 0, string: data.author)
  NPRPC.marshal_string(buffer: buffer, offset: offset + 8, string: data.body)
  NPRPC.marshal_string(buffer: buffer, offset: offset + 16, string: data.created_at)
}

// MARK: - Unmarshal ChatEnvelope
public func unmarshal_ChatEnvelope(buffer: UnsafeRawPointer, offset: Int) -> ChatEnvelope {
  var result = ChatEnvelope()
  result.author = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 0)
  result.body = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 8)
  result.created_at = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 16)
  return result
}

public struct PresenceEvent: Codable, Sendable {
  public var user_name: String = ""
  public var kind: PresenceEventKind = .joined

  public init() {}

  public init(user_name: String, kind: PresenceEventKind)   {
    self.user_name = user_name
    self.kind = kind
  }
}


// MARK: - Marshal PresenceEvent
public func marshal_PresenceEvent(buffer: FlatBuffer, offset: Int, data: PresenceEvent) {
  guard let buf = buffer.data else { return }
  NPRPC.marshal_string(buffer: buffer, offset: offset + 0, string: data.user_name)
  buf.storeBytes(of: data.kind.rawValue, toByteOffset: offset + 8, as: Int32.self)
}

// MARK: - Unmarshal PresenceEvent
public func unmarshal_PresenceEvent(buffer: UnsafeRawPointer, offset: Int) -> PresenceEvent {
  var result = PresenceEvent()
  result.user_name = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 0)
  result.kind = PresenceEventKind(rawValue: buffer.load(fromByteOffset: offset + 8, as: Int32.self))!
  return result
}

public struct ChatServerEvent: Codable, Sendable {
  public var message: ChatEnvelope = ChatEnvelope()
  public var presence: PresenceEvent = PresenceEvent()

  public init() {}

  public init(message: ChatEnvelope, presence: PresenceEvent)   {
    self.message = message
    self.presence = presence
  }
}


// MARK: - Marshal ChatServerEvent
public func marshal_ChatServerEvent(buffer: FlatBuffer, offset: Int, data: ChatServerEvent) {
  marshal_ChatEnvelope(buffer: buffer, offset: offset + 0, data: data.message)
  marshal_PresenceEvent(buffer: buffer, offset: offset + 24, data: data.presence)
}

// MARK: - Unmarshal ChatServerEvent
public func unmarshal_ChatServerEvent(buffer: UnsafeRawPointer, offset: Int) -> ChatServerEvent {
  var result = ChatServerEvent()
  result.message = unmarshal_ChatEnvelope(buffer: buffer, offset: offset + 0)
  result.presence = unmarshal_PresenceEvent(buffer: buffer, offset: offset + 24)
  return result
}

fileprivate struct live_blog_M1: Codable, Sendable {
  public var _1: UInt32 = 0
  public var _2: UInt32 = 0

  public init() {}

  public init(_1: UInt32, _2: UInt32)   {
    self._1 = _1
    self._2 = _2
  }
}


// MARK: - Marshal live_blog_M1
fileprivate func marshal_live_blog_M1(buffer: FlatBuffer, offset: Int, data: live_blog_M1) {
  guard let buf = buffer.data else { return }
  buf.storeBytes(of: data._1, toByteOffset: offset + 0, as: UInt32.self)
  buf.storeBytes(of: data._2, toByteOffset: offset + 4, as: UInt32.self)
}

// MARK: - Unmarshal live_blog_M1
fileprivate func unmarshal_live_blog_M1(buffer: UnsafeRawPointer, offset: Int) -> live_blog_M1 {
  var result = live_blog_M1()
  result._1 = buffer.load(fromByteOffset: offset + 0, as: UInt32.self)
  result._2 = buffer.load(fromByteOffset: offset + 4, as: UInt32.self)
  return result
}

fileprivate struct live_blog_M2: Codable, Sendable {
  public var _1: PostPage = PostPage()

  public init() {}

  public init(_1: PostPage)   {
    self._1 = _1
  }
}


// MARK: - Marshal live_blog_M2
fileprivate func marshal_live_blog_M2(buffer: FlatBuffer, offset: Int, data: live_blog_M2) {
  marshal_PostPage(buffer: buffer, offset: offset + 0, data: data._1)
}

// MARK: - Unmarshal live_blog_M2
fileprivate func unmarshal_live_blog_M2(buffer: UnsafeRawPointer, offset: Int) -> live_blog_M2 {
  var result = live_blog_M2()
  result._1 = unmarshal_PostPage(buffer: buffer, offset: offset + 0)
  return result
}

fileprivate struct live_blog_M3: Codable, Sendable {
  public var _1: String = ""

  public init() {}

  public init(_1: String)   {
    self._1 = _1
  }
}


// MARK: - Marshal live_blog_M3
fileprivate func marshal_live_blog_M3(buffer: FlatBuffer, offset: Int, data: live_blog_M3) {
  NPRPC.marshal_string(buffer: buffer, offset: offset + 0, string: data._1)
}

// MARK: - Unmarshal live_blog_M3
fileprivate func unmarshal_live_blog_M3(buffer: UnsafeRawPointer, offset: Int) -> live_blog_M3 {
  var result = live_blog_M3()
  result._1 = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 0)
  return result
}

fileprivate struct live_blog_M4: Codable, Sendable {
  public var _1: PostDetail = PostDetail()

  public init() {}

  public init(_1: PostDetail)   {
    self._1 = _1
  }
}


// MARK: - Marshal live_blog_M4
fileprivate func marshal_live_blog_M4(buffer: FlatBuffer, offset: Int, data: live_blog_M4) {
  marshal_PostDetail(buffer: buffer, offset: offset + 0, data: data._1)
}

// MARK: - Unmarshal live_blog_M4
fileprivate func unmarshal_live_blog_M4(buffer: UnsafeRawPointer, offset: Int) -> live_blog_M4 {
  var result = live_blog_M4()
  result._1 = unmarshal_PostDetail(buffer: buffer, offset: offset + 0)
  return result
}

fileprivate struct live_blog_M5: Codable, Sendable {
  public var _1: UInt64 = 0
  public var _2: UInt32 = 0
  public var _3: UInt32 = 0

  public init() {}

  public init(_1: UInt64, _2: UInt32, _3: UInt32)   {
    self._1 = _1
    self._2 = _2
    self._3 = _3
  }
}


// MARK: - Marshal live_blog_M5
fileprivate func marshal_live_blog_M5(buffer: FlatBuffer, offset: Int, data: live_blog_M5) {
  guard let buf = buffer.data else { return }
  buf.storeBytes(of: data._1, toByteOffset: offset + 0, as: UInt64.self)
  buf.storeBytes(of: data._2, toByteOffset: offset + 8, as: UInt32.self)
  buf.storeBytes(of: data._3, toByteOffset: offset + 12, as: UInt32.self)
}

// MARK: - Unmarshal live_blog_M5
fileprivate func unmarshal_live_blog_M5(buffer: UnsafeRawPointer, offset: Int) -> live_blog_M5 {
  var result = live_blog_M5()
  result._1 = buffer.load(fromByteOffset: offset + 0, as: UInt64.self)
  result._2 = buffer.load(fromByteOffset: offset + 8, as: UInt32.self)
  result._3 = buffer.load(fromByteOffset: offset + 12, as: UInt32.self)
  return result
}

fileprivate struct live_blog_M6: Codable, Sendable {
  public var _1: [Comment] = []

  public init() {}

  public init(_1: [Comment])   {
    self._1 = _1
  }
}


// MARK: - Marshal live_blog_M6
fileprivate func marshal_live_blog_M6(buffer: FlatBuffer, offset: Int, data: live_blog_M6) {
  NPRPC.marshal_struct_vector(buffer: buffer, offset: offset + 0, vector: data._1, elementSize: 32, elementAlignment: 8) { buf, off, elem in
    marshal_Comment(buffer: buf, offset: off, data: elem)
  }
}

// MARK: - Unmarshal live_blog_M6
fileprivate func unmarshal_live_blog_M6(buffer: UnsafeRawPointer, offset: Int) -> live_blog_M6 {
  var result = live_blog_M6()
  result._1 = NPRPC.unmarshal_struct_vector(buffer: buffer, offset: offset + 0, elementSize: 32) { buf, off in
    unmarshal_Comment(buffer: buf, offset: off)
  }
  return result
}

fileprivate struct live_blog_M7: Codable, Sendable {
  public var _1: String = ""
  public var _2: UInt32 = 0
  public var _3: UInt32 = 0

  public init() {}

  public init(_1: String, _2: UInt32, _3: UInt32)   {
    self._1 = _1
    self._2 = _2
    self._3 = _3
  }
}


// MARK: - Marshal live_blog_M7
fileprivate func marshal_live_blog_M7(buffer: FlatBuffer, offset: Int, data: live_blog_M7) {
  guard let buf = buffer.data else { return }
  NPRPC.marshal_string(buffer: buffer, offset: offset + 0, string: data._1)
  buf.storeBytes(of: data._2, toByteOffset: offset + 8, as: UInt32.self)
  buf.storeBytes(of: data._3, toByteOffset: offset + 12, as: UInt32.self)
}

// MARK: - Unmarshal live_blog_M7
fileprivate func unmarshal_live_blog_M7(buffer: UnsafeRawPointer, offset: Int) -> live_blog_M7 {
  var result = live_blog_M7()
  result._1 = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 0)
  result._2 = buffer.load(fromByteOffset: offset + 8, as: UInt32.self)
  result._3 = buffer.load(fromByteOffset: offset + 12, as: UInt32.self)
  return result
}

fileprivate struct live_blog_M8: Codable, Sendable {
  public var _1: [PostPreview] = []

  public init() {}

  public init(_1: [PostPreview])   {
    self._1 = _1
  }
}


// MARK: - Marshal live_blog_M8
fileprivate func marshal_live_blog_M8(buffer: FlatBuffer, offset: Int, data: live_blog_M8) {
  NPRPC.marshal_struct_vector(buffer: buffer, offset: offset + 0, vector: data._1, elementSize: 88, elementAlignment: 8) { buf, off, elem in
    marshal_PostPreview(buffer: buf, offset: off, data: elem)
  }
}

// MARK: - Unmarshal live_blog_M8
fileprivate func unmarshal_live_blog_M8(buffer: UnsafeRawPointer, offset: Int) -> live_blog_M8 {
  var result = live_blog_M8()
  result._1 = NPRPC.unmarshal_struct_vector(buffer: buffer, offset: offset + 0, elementSize: 88) { buf, off in
    unmarshal_PostPreview(buffer: buf, offset: off)
  }
  return result
}

fileprivate struct live_blog_M9: Codable, Sendable {
  public var _1: AuthorPreview = AuthorPreview()

  public init() {}

  public init(_1: AuthorPreview)   {
    self._1 = _1
  }
}


// MARK: - Marshal live_blog_M9
fileprivate func marshal_live_blog_M9(buffer: FlatBuffer, offset: Int, data: live_blog_M9) {
  marshal_AuthorPreview(buffer: buffer, offset: offset + 0, data: data._1)
}

// MARK: - Unmarshal live_blog_M9
fileprivate func unmarshal_live_blog_M9(buffer: UnsafeRawPointer, offset: Int) -> live_blog_M9 {
  var result = live_blog_M9()
  result._1 = unmarshal_AuthorPreview(buffer: buffer, offset: offset + 0)
  return result
}

public protocol BlogServiceProtocol {
  func listPosts(page: UInt32, page_size: UInt32) -> PostPage
  func getPost(slug: String) -> PostDetail
  func listComments(post_id: UInt64, page: UInt32, page_size: UInt32) -> [Comment]
  func listAuthorPosts(author_slug: String, page: UInt32, page_size: UInt32) -> [PostPreview]
  func getAuthor(author_slug: String) -> AuthorPreview
}

// Client proxy for BlogService
// Pure Swift implementation with direct marshalling
final public class BlogService: NPRPCObject, @unchecked Sendable {
  public override class var classId: String {
    "live_blog/live_blog.BlogService"
  }

  public required init(handle: UnsafeMutableRawPointer)   {
    super.init(handle: handle)
  }

  public required init(from decoder: Decoder) throws   {
    try super.init(from: decoder)
  }

  public func listPosts(page: UInt32, page_size: UInt32) throws -> PostPage   {
    // Prepare buffer
    let buffer = FlatBuffer()
    buffer.prepare(40)
    buffer.commit(40)
    guard let data = buffer.data else { throw BufferError(message: "Failed to get buffer data") }

    // Write message header
    data.storeBytes(of: UInt32(0), toByteOffset: 0, as: UInt32.self)  // size (set later)
    data.storeBytes(of: UInt32(0), toByteOffset: 4, as: UInt32.self)  // msg_id: FunctionCall (MessageId enum value 0)
    data.storeBytes(of: UInt32(0), toByteOffset: 8, as: UInt32.self)  // msg_type: Request
    data.storeBytes(of: UInt32(0), toByteOffset: 12, as: UInt32.self) // reserved

    // Write call header
    data.storeBytes(of: poaIdx, toByteOffset: 16, as: UInt16.self)
    data.storeBytes(of: UInt8(0), toByteOffset: 18, as: UInt8.self)  // interface_idx
    data.storeBytes(of: UInt8(0), toByteOffset: 19, as: UInt8.self)  // function_idx
    data.storeBytes(of: objectId, toByteOffset: 24, as: UInt64.self)

    // Marshal input arguments
    var inArgs = live_blog_M1()
    inArgs._1 = page
    inArgs._2 = page_size
    marshal_live_blog_M1(buffer: buffer, offset: 32, data: inArgs)

    guard let finalData = buffer.data else { throw BufferError(message: "Failed to get buffer data") }
    finalData.storeBytes(of: UInt32(buffer.size - 4), toByteOffset: 0, as: UInt32.self)

    // Send and receive
    try sendReceive(buffer: buffer, timeout: timeout)

    // Handle reply
    let stdReply = try handleStandardReply(buffer: buffer)
    if stdReply != -1 { throw UnexpectedReplyError(message: "Unexpected reply") }

    guard let responseData = buffer.data else { throw BufferError(message: "Failed to get response data") }
    let out = unmarshal_live_blog_M2(buffer: responseData, offset: 16)
    return out._1
  }

  public func getPost(slug: String) throws -> PostDetail   {
    // Prepare buffer
    let buffer = FlatBuffer()
    buffer.prepare(168)
    buffer.commit(40)
    guard let data = buffer.data else { throw BufferError(message: "Failed to get buffer data") }

    // Write message header
    data.storeBytes(of: UInt32(0), toByteOffset: 0, as: UInt32.self)  // size (set later)
    data.storeBytes(of: UInt32(0), toByteOffset: 4, as: UInt32.self)  // msg_id: FunctionCall (MessageId enum value 0)
    data.storeBytes(of: UInt32(0), toByteOffset: 8, as: UInt32.self)  // msg_type: Request
    data.storeBytes(of: UInt32(0), toByteOffset: 12, as: UInt32.self) // reserved

    // Write call header
    data.storeBytes(of: poaIdx, toByteOffset: 16, as: UInt16.self)
    data.storeBytes(of: UInt8(0), toByteOffset: 18, as: UInt8.self)  // interface_idx
    data.storeBytes(of: UInt8(1), toByteOffset: 19, as: UInt8.self)  // function_idx
    data.storeBytes(of: objectId, toByteOffset: 24, as: UInt64.self)

    // Marshal input arguments
    var inArgs = live_blog_M3()
    inArgs._1 = slug
    marshal_live_blog_M3(buffer: buffer, offset: 32, data: inArgs)

    guard let finalData = buffer.data else { throw BufferError(message: "Failed to get buffer data") }
    finalData.storeBytes(of: UInt32(buffer.size - 4), toByteOffset: 0, as: UInt32.self)

    // Send and receive
    try sendReceive(buffer: buffer, timeout: timeout)

    // Handle reply
    let stdReply = try handleStandardReply(buffer: buffer)
    if stdReply != -1 { throw UnexpectedReplyError(message: "Unexpected reply") }

    guard let responseData = buffer.data else { throw BufferError(message: "Failed to get response data") }
    let out = unmarshal_live_blog_M4(buffer: responseData, offset: 16)
    return out._1
  }

  public func listComments(post_id: UInt64, page: UInt32, page_size: UInt32) throws -> [Comment]   {
    // Prepare buffer
    let buffer = FlatBuffer()
    buffer.prepare(48)
    buffer.commit(48)
    guard let data = buffer.data else { throw BufferError(message: "Failed to get buffer data") }

    // Write message header
    data.storeBytes(of: UInt32(0), toByteOffset: 0, as: UInt32.self)  // size (set later)
    data.storeBytes(of: UInt32(0), toByteOffset: 4, as: UInt32.self)  // msg_id: FunctionCall (MessageId enum value 0)
    data.storeBytes(of: UInt32(0), toByteOffset: 8, as: UInt32.self)  // msg_type: Request
    data.storeBytes(of: UInt32(0), toByteOffset: 12, as: UInt32.self) // reserved

    // Write call header
    data.storeBytes(of: poaIdx, toByteOffset: 16, as: UInt16.self)
    data.storeBytes(of: UInt8(0), toByteOffset: 18, as: UInt8.self)  // interface_idx
    data.storeBytes(of: UInt8(2), toByteOffset: 19, as: UInt8.self)  // function_idx
    data.storeBytes(of: objectId, toByteOffset: 24, as: UInt64.self)

    // Marshal input arguments
    var inArgs = live_blog_M5()
    inArgs._1 = post_id
    inArgs._2 = page
    inArgs._3 = page_size
    marshal_live_blog_M5(buffer: buffer, offset: 32, data: inArgs)

    guard let finalData = buffer.data else { throw BufferError(message: "Failed to get buffer data") }
    finalData.storeBytes(of: UInt32(buffer.size - 4), toByteOffset: 0, as: UInt32.self)

    // Send and receive
    try sendReceive(buffer: buffer, timeout: timeout)

    // Handle reply
    let stdReply = try handleStandardReply(buffer: buffer)
    if stdReply != -1 { throw UnexpectedReplyError(message: "Unexpected reply") }

    guard let responseData = buffer.data else { throw BufferError(message: "Failed to get response data") }
    let out = unmarshal_live_blog_M6(buffer: responseData, offset: 16)
    return out._1
  }

  public func listAuthorPosts(author_slug: String, page: UInt32, page_size: UInt32) throws -> [PostPreview]   {
    // Prepare buffer
    let buffer = FlatBuffer()
    buffer.prepare(176)
    buffer.commit(48)
    guard let data = buffer.data else { throw BufferError(message: "Failed to get buffer data") }

    // Write message header
    data.storeBytes(of: UInt32(0), toByteOffset: 0, as: UInt32.self)  // size (set later)
    data.storeBytes(of: UInt32(0), toByteOffset: 4, as: UInt32.self)  // msg_id: FunctionCall (MessageId enum value 0)
    data.storeBytes(of: UInt32(0), toByteOffset: 8, as: UInt32.self)  // msg_type: Request
    data.storeBytes(of: UInt32(0), toByteOffset: 12, as: UInt32.self) // reserved

    // Write call header
    data.storeBytes(of: poaIdx, toByteOffset: 16, as: UInt16.self)
    data.storeBytes(of: UInt8(0), toByteOffset: 18, as: UInt8.self)  // interface_idx
    data.storeBytes(of: UInt8(3), toByteOffset: 19, as: UInt8.self)  // function_idx
    data.storeBytes(of: objectId, toByteOffset: 24, as: UInt64.self)

    // Marshal input arguments
    var inArgs = live_blog_M7()
    inArgs._1 = author_slug
    inArgs._2 = page
    inArgs._3 = page_size
    marshal_live_blog_M7(buffer: buffer, offset: 32, data: inArgs)

    guard let finalData = buffer.data else { throw BufferError(message: "Failed to get buffer data") }
    finalData.storeBytes(of: UInt32(buffer.size - 4), toByteOffset: 0, as: UInt32.self)

    // Send and receive
    try sendReceive(buffer: buffer, timeout: timeout)

    // Handle reply
    let stdReply = try handleStandardReply(buffer: buffer)
    if stdReply != -1 { throw UnexpectedReplyError(message: "Unexpected reply") }

    guard let responseData = buffer.data else { throw BufferError(message: "Failed to get response data") }
    let out = unmarshal_live_blog_M8(buffer: responseData, offset: 16)
    return out._1
  }

  public func getAuthor(author_slug: String) throws -> AuthorPreview   {
    // Prepare buffer
    let buffer = FlatBuffer()
    buffer.prepare(168)
    buffer.commit(40)
    guard let data = buffer.data else { throw BufferError(message: "Failed to get buffer data") }

    // Write message header
    data.storeBytes(of: UInt32(0), toByteOffset: 0, as: UInt32.self)  // size (set later)
    data.storeBytes(of: UInt32(0), toByteOffset: 4, as: UInt32.self)  // msg_id: FunctionCall (MessageId enum value 0)
    data.storeBytes(of: UInt32(0), toByteOffset: 8, as: UInt32.self)  // msg_type: Request
    data.storeBytes(of: UInt32(0), toByteOffset: 12, as: UInt32.self) // reserved

    // Write call header
    data.storeBytes(of: poaIdx, toByteOffset: 16, as: UInt16.self)
    data.storeBytes(of: UInt8(0), toByteOffset: 18, as: UInt8.self)  // interface_idx
    data.storeBytes(of: UInt8(4), toByteOffset: 19, as: UInt8.self)  // function_idx
    data.storeBytes(of: objectId, toByteOffset: 24, as: UInt64.self)

    // Marshal input arguments
    var inArgs = live_blog_M3()
    inArgs._1 = author_slug
    marshal_live_blog_M3(buffer: buffer, offset: 32, data: inArgs)

    guard let finalData = buffer.data else { throw BufferError(message: "Failed to get buffer data") }
    finalData.storeBytes(of: UInt32(buffer.size - 4), toByteOffset: 0, as: UInt32.self)

    // Send and receive
    try sendReceive(buffer: buffer, timeout: timeout)

    // Handle reply
    let stdReply = try handleStandardReply(buffer: buffer)
    if stdReply != -1 { throw UnexpectedReplyError(message: "Unexpected reply") }

    guard let responseData = buffer.data else { throw BufferError(message: "Failed to get response data") }
    let out = unmarshal_live_blog_M9(buffer: responseData, offset: 16)
    return out._1
  }

}

// Servant base for BlogService
open class BlogServiceServant: NPRPCServant, BlogServiceProtocol, @unchecked Sendable {
  public override init() { super.init() }

  public override func getClass() -> String   {
    return "live_blog/live_blog.BlogService"
  }

  open func listPosts(page: UInt32, page_size: UInt32) -> PostPage   {
    fatalError("Subclass must implement listPosts")
  }

  open func getPost(slug: String) -> PostDetail   {
    fatalError("Subclass must implement getPost")
  }

  open func listComments(post_id: UInt64, page: UInt32, page_size: UInt32) -> [Comment]   {
    fatalError("Subclass must implement listComments")
  }

  open func listAuthorPosts(author_slug: String, page: UInt32, page_size: UInt32) -> [PostPreview]   {
    fatalError("Subclass must implement listAuthorPosts")
  }

  open func getAuthor(author_slug: String) -> AuthorPreview   {
    fatalError("Subclass must implement getAuthor")
  }

  // Dispatch incoming RPC calls
  public override func dispatch(buffer: FlatBuffer, remoteEndpoint: NPRPCEndpoint)   {
    guard let data = buffer.data else { return }

    // Read function index from CallHeader
    let functionIdx = data.load(fromByteOffset: (16 + MemoryLayout<NPRPC.impl.CallHeader>.offset(of: \NPRPC.impl.CallHeader.function_idx)!), as: UInt8.self)

    switch functionIdx     {
      case 0: // ListPosts
        // Unmarshal input arguments
        let ia = unmarshal_live_blog_M1(buffer: data, offset: 32)
        // Prepare output buffer
        let obuf = buffer
        obuf.consume(obuf.size)
        obuf.prepare(164)
        obuf.commit(36)
        
        let __ret_val = listPosts(page: ia._1, page_size: ia._2)
        // Marshal output arguments
        var out_data = live_blog_M2()
        out_data._1 = __ret_val

        marshal_live_blog_M2(buffer: buffer, offset: 16, data: out_data)
        guard let outData = buffer.data else { return }
        outData.storeBytes(of: UInt32(buffer.size - 4), toByteOffset: 0, as: UInt32.self)
        outData.storeBytes(of: impl.MessageId.blockResponse.rawValue, toByteOffset: 4, as: Int32.self)
        outData.storeBytes(of: impl.MessageType.answer.rawValue, toByteOffset: 8, as: Int32.self)
      case 1: // GetPost
        // Unmarshal input arguments
        let ia = unmarshal_live_blog_M3(buffer: data, offset: 32)
        // Prepare output buffer
        let obuf = buffer
        obuf.consume(obuf.size)
        obuf.prepare(240)
        obuf.commit(112)
        
        let __ret_val = getPost(slug: ia._1)
        // Marshal output arguments
        var out_data = live_blog_M4()
        out_data._1 = __ret_val

        marshal_live_blog_M4(buffer: buffer, offset: 16, data: out_data)
        guard let outData = buffer.data else { return }
        outData.storeBytes(of: UInt32(buffer.size - 4), toByteOffset: 0, as: UInt32.self)
        outData.storeBytes(of: impl.MessageId.blockResponse.rawValue, toByteOffset: 4, as: Int32.self)
        outData.storeBytes(of: impl.MessageType.answer.rawValue, toByteOffset: 8, as: Int32.self)
      case 2: // ListComments
        // Unmarshal input arguments
        let ia = unmarshal_live_blog_M5(buffer: data, offset: 32)
        // Prepare output buffer
        let obuf = buffer
        obuf.consume(obuf.size)
        obuf.prepare(152)
        obuf.commit(24)
        
        let __ret_val = listComments(post_id: ia._1, page: ia._2, page_size: ia._3)
        // Marshal output arguments
        var out_data = live_blog_M6()
        out_data._1 = __ret_val

        marshal_live_blog_M6(buffer: buffer, offset: 16, data: out_data)
        guard let outData = buffer.data else { return }
        outData.storeBytes(of: UInt32(buffer.size - 4), toByteOffset: 0, as: UInt32.self)
        outData.storeBytes(of: impl.MessageId.blockResponse.rawValue, toByteOffset: 4, as: Int32.self)
        outData.storeBytes(of: impl.MessageType.answer.rawValue, toByteOffset: 8, as: Int32.self)
      case 3: // ListAuthorPosts
        // Unmarshal input arguments
        let ia = unmarshal_live_blog_M7(buffer: data, offset: 32)
        // Prepare output buffer
        let obuf = buffer
        obuf.consume(obuf.size)
        obuf.prepare(152)
        obuf.commit(24)
        
        let __ret_val = listAuthorPosts(author_slug: ia._1, page: ia._2, page_size: ia._3)
        // Marshal output arguments
        var out_data = live_blog_M8()
        out_data._1 = __ret_val

        marshal_live_blog_M8(buffer: buffer, offset: 16, data: out_data)
        guard let outData = buffer.data else { return }
        outData.storeBytes(of: UInt32(buffer.size - 4), toByteOffset: 0, as: UInt32.self)
        outData.storeBytes(of: impl.MessageId.blockResponse.rawValue, toByteOffset: 4, as: Int32.self)
        outData.storeBytes(of: impl.MessageType.answer.rawValue, toByteOffset: 8, as: Int32.self)
      case 4: // GetAuthor
        // Unmarshal input arguments
        let ia = unmarshal_live_blog_M3(buffer: data, offset: 32)
        // Prepare output buffer
        let obuf = buffer
        obuf.consume(obuf.size)
        obuf.prepare(184)
        obuf.commit(56)
        
        let __ret_val = getAuthor(author_slug: ia._1)
        // Marshal output arguments
        var out_data = live_blog_M9()
        out_data._1 = __ret_val

        marshal_live_blog_M9(buffer: buffer, offset: 16, data: out_data)
        guard let outData = buffer.data else { return }
        outData.storeBytes(of: UInt32(buffer.size - 4), toByteOffset: 0, as: UInt32.self)
        outData.storeBytes(of: impl.MessageId.blockResponse.rawValue, toByteOffset: 4, as: Int32.self)
        outData.storeBytes(of: impl.MessageType.answer.rawValue, toByteOffset: 8, as: Int32.self)
      default:
        makeSimpleAnswer(buffer: buffer, messageId: impl.MessageId.error_UnknownFunctionIdx)
    } // switch
  } // dispatch
}

fileprivate struct live_blog_M10: Codable, Sendable {
  public var _1: UInt64 = 0
  public var _2: String = ""

  public init() {}

  public init(_1: UInt64, _2: String)   {
    self._1 = _1
    self._2 = _2
  }
}


// MARK: - Marshal live_blog_M10
fileprivate func marshal_live_blog_M10(buffer: FlatBuffer, offset: Int, data: live_blog_M10) {
  guard let buf = buffer.data else { return }
  buf.storeBytes(of: data._1, toByteOffset: offset + 0, as: UInt64.self)
  NPRPC.marshal_string(buffer: buffer, offset: offset + 8, string: data._2)
}

// MARK: - Unmarshal live_blog_M10
fileprivate func unmarshal_live_blog_M10(buffer: UnsafeRawPointer, offset: Int) -> live_blog_M10 {
  var result = live_blog_M10()
  result._1 = buffer.load(fromByteOffset: offset + 0, as: UInt64.self)
  result._2 = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 8)
  return result
}

public protocol ChatServiceProtocol {
  func joinPostChat(post_id: UInt64, user_name: String, stream: NPRPCBidiStream<ChatServerEvent, ChatEnvelope>) async
}

// Client proxy for ChatService
// Pure Swift implementation with direct marshalling
final public class ChatService: NPRPCObject, @unchecked Sendable {
  public override class var classId: String {
    "live_blog/live_blog.ChatService"
  }

  public required init(handle: UnsafeMutableRawPointer)   {
    super.init(handle: handle)
  }

  public required init(from decoder: Decoder) throws   {
    try super.init(from: decoder)
  }

  public func joinPostChat(post_id: UInt64, user_name: String) throws -> NPRPCBidiStream<ChatEnvelope, ChatServerEvent>   {
    let streamId = nprpc_generate_stream_id()

    // Prepare StreamInit buffer
    let buffer = FlatBuffer()
    buffer.prepare(192)
    buffer.commit(64)
    guard let data = buffer.data else { throw BufferError(message: "Failed to get buffer data") }

    // Write StreamInit message header
    data.storeBytes(of: UInt32(0), toByteOffset: 0, as: UInt32.self)  // size (set later)
    data.storeBytes(of: impl.MessageId.streamInitialization.rawValue, toByteOffset: 4, as: Int32.self)
    data.storeBytes(of: impl.MessageType.request.rawValue, toByteOffset: 8, as: Int32.self)
    data.storeBytes(of: UInt32(0), toByteOffset: 12, as: UInt32.self)  // reserved

    // Write StreamInit fields
    data.storeBytes(of: streamId, toByteOffset: 16, as: UInt64.self)  // offset 0
    data.storeBytes(of: poaIdx, toByteOffset: 24, as: UInt16.self)  // offset 8
    data.storeBytes(of: UInt8(0), toByteOffset: 26, as: UInt8.self)  // interface_idx at offset 10
    data.storeBytes(of: objectId, toByteOffset: 32, as: UInt64.self)  // offset 16 (after 5-byte pad)
    data.storeBytes(of: UInt8(0), toByteOffset: 40, as: UInt8.self)  // func_idx at offset 24
    data.storeBytes(of: impl.StreamKind.bidi.rawValue, toByteOffset: 41, as: Int32.self)

    // Marshal input arguments
    var inArgs = live_blog_M10()
    inArgs._1 = post_id
    inArgs._2 = user_name
    marshal_live_blog_M10(buffer: buffer, offset: 48, data: inArgs)

    guard let finalData = buffer.data else { throw BufferError(message: "Failed to get buffer data") }
    finalData.storeBytes(of: UInt32(buffer.size - 4), toByteOffset: 0, as: UInt32.self)

    let stream = try NPRPC.createObjectBidiStream(objectHandle: self.handle, streamId: streamId, buffer: buffer, initialPayloadCapacity: 152, serializer: { (buffer: FlatBuffer, offset: Int, value: ChatEnvelope) in NPRPC.marshal_stream_struct(buffer: buffer, offset: offset, rootSize: 24, value: value) { buf, off, elem in marshal_ChatEnvelope(buffer: buf, offset: off, data: elem) } }, deserializer: { (data: UnsafeRawPointer, _: Int) in unmarshal_ChatServerEvent(buffer: data, offset: 0) })
    let result = nprpc_stream_send_init(self.handle, buffer.handle, self.timeout)
    if result != 0 { throw RuntimeError(message: "Failed to send StreamInit") }
    return stream
  }

}

// Servant base for ChatService
open class ChatServiceServant: NPRPCServant, ChatServiceProtocol, @unchecked Sendable {
  public override init() { super.init() }

  public override func getClass() -> String   {
    return "live_blog/live_blog.ChatService"
  }

  open func joinPostChat(post_id: UInt64, user_name: String, stream: NPRPCBidiStream<ChatServerEvent, ChatEnvelope>) async   {
    fatalError("Subclass must implement joinPostChat")
  }

  // Dispatch incoming RPC calls
  public override func dispatch(buffer: FlatBuffer, remoteEndpoint: NPRPCEndpoint)   {
    guard let data = buffer.data else { return }

    // Check message type to route streaming vs regular calls
    let msgId = data.load(fromByteOffset: MemoryLayout<NPRPC.impl.Header>.offset(of: \NPRPC.impl.Header.msg_id)!, as: Int32.self)

    if msgId == impl.MessageId.streamInitialization.rawValue     {
      let streamFuncIdx = data.load(fromByteOffset: (16 + MemoryLayout<NPRPC.impl.StreamInit>.offset(of: \NPRPC.impl.StreamInit.func_idx)!), as: UInt8.self)
      switch streamFuncIdx       {
        case 0: // JoinPostChat
          // Streaming method dispatch
          guard let data = buffer.data else { return }
          let streamId = data.load(fromByteOffset: (16 + MemoryLayout<NPRPC.impl.StreamInit>.offset(of: \NPRPC.impl.StreamInit.stream_id)!), as: UInt64.self)

          // Unmarshal input arguments
          let ia = unmarshal_live_blog_M10(buffer: data, offset: 48)

          // Get stream_manager for streaming (heap-allocated, survives after dispatch returns)
          guard let sessionCtx = self.sessionContext,
                let streamManager = nprpc_get_stream_manager(sessionCtx) else {
            makeSimpleAnswer(buffer: buffer, messageId: impl.MessageId.error_BadInput)
            return
          }
          let stream = NPRPC.createStreamManagerBidiStream(streamManager: streamManager, streamId: streamId, buffer: buffer, initialPayloadCapacity: 164, serializer: { (buffer: FlatBuffer, offset: Int, value: ChatServerEvent) in NPRPC.marshal_stream_struct(buffer: buffer, offset: offset, rootSize: 36, value: value) { buf, off, elem in marshal_ChatServerEvent(buffer: buf, offset: off, data: elem) } }, deserializer: { (data: UnsafeRawPointer, _: Int) in unmarshal_ChatEnvelope(buffer: data, offset: 0) })
          makeSimpleAnswer(buffer: buffer, messageId: impl.MessageId.success)
          Task {
            await joinPostChat(post_id: ia._1, user_name: ia._2, stream: stream)
          }

        default:
          makeSimpleAnswer(buffer: buffer, messageId: impl.MessageId.error_UnknownFunctionIdx)
      } // switch streamFuncIdx
      return
    }

    // Read function index from CallHeader
    let functionIdx = data.load(fromByteOffset: (16 + MemoryLayout<NPRPC.impl.CallHeader>.offset(of: \NPRPC.impl.CallHeader.function_idx)!), as: UInt8.self)

    switch functionIdx     {
      default:
        makeSimpleAnswer(buffer: buffer, messageId: impl.MessageId.error_UnknownFunctionIdx)
    } // switch
  } // dispatch
}

fileprivate struct live_blog_M11: Codable, Sendable {
  public var _1: UInt64 = 0

  public init() {}

  public init(_1: UInt64)   {
    self._1 = _1
  }
}


// MARK: - Marshal live_blog_M11
fileprivate func marshal_live_blog_M11(buffer: FlatBuffer, offset: Int, data: live_blog_M11) {
  guard let buf = buffer.data else { return }
  buf.storeBytes(of: data._1, toByteOffset: offset + 0, as: UInt64.self)
}

// MARK: - Unmarshal live_blog_M11
fileprivate func unmarshal_live_blog_M11(buffer: UnsafeRawPointer, offset: Int) -> live_blog_M11 {
  var result = live_blog_M11()
  result._1 = buffer.load(fromByteOffset: offset + 0, as: UInt64.self)
  return result
}

public protocol MediaServiceProtocol {
  func openPostVideo(post_id: UInt64) -> AsyncStream<binary>
}

// Client proxy for MediaService
// Pure Swift implementation with direct marshalling
final public class MediaService: NPRPCObject, @unchecked Sendable {
  public override class var classId: String {
    "live_blog/live_blog.MediaService"
  }

  public required init(handle: UnsafeMutableRawPointer)   {
    super.init(handle: handle)
  }

  public required init(from decoder: Decoder) throws   {
    try super.init(from: decoder)
  }

  public func openPostVideo(post_id: UInt64) throws -> NPRPCStreamReader<binary>   {
    let streamId = nprpc_generate_stream_id()

    // Prepare StreamInit buffer
    let buffer = FlatBuffer()
    buffer.prepare(56)
    buffer.commit(56)
    guard let data = buffer.data else { throw BufferError(message: "Failed to get buffer data") }

    // Write StreamInit message header
    data.storeBytes(of: UInt32(0), toByteOffset: 0, as: UInt32.self)  // size (set later)
    data.storeBytes(of: impl.MessageId.streamInitialization.rawValue, toByteOffset: 4, as: Int32.self)
    data.storeBytes(of: impl.MessageType.request.rawValue, toByteOffset: 8, as: Int32.self)
    data.storeBytes(of: UInt32(0), toByteOffset: 12, as: UInt32.self)  // reserved

    // Write StreamInit fields
    data.storeBytes(of: streamId, toByteOffset: 16, as: UInt64.self)  // offset 0
    data.storeBytes(of: poaIdx, toByteOffset: 24, as: UInt16.self)  // offset 8
    data.storeBytes(of: UInt8(0), toByteOffset: 26, as: UInt8.self)  // interface_idx at offset 10
    data.storeBytes(of: objectId, toByteOffset: 32, as: UInt64.self)  // offset 16 (after 5-byte pad)
    data.storeBytes(of: UInt8(0), toByteOffset: 40, as: UInt8.self)  // func_idx at offset 24
    data.storeBytes(of: impl.StreamKind.server.rawValue, toByteOffset: 41, as: Int32.self)

    // Marshal input arguments
    var inArgs = live_blog_M11()
    inArgs._1 = post_id
    marshal_live_blog_M11(buffer: buffer, offset: 48, data: inArgs)

    guard let finalData = buffer.data else { throw BufferError(message: "Failed to get buffer data") }
    finalData.storeBytes(of: UInt32(buffer.size - 4), toByteOffset: 0, as: UInt32.self)

    let reader = NPRPC.createObjectStreamReader(objectHandle: self.handle, streamId: streamId, buffer: buffer, deserializer: { (data: UnsafeRawPointer, _: Int) in NPRPC.unmarshal_stream_fundamental_vector(data: data) as [UInt8] })
    let result = nprpc_stream_send_init(self.handle, buffer.handle, self.timeout)
    if result != 0 { throw RuntimeError(message: "Failed to send StreamInit") }
    return reader
  }

}

// Servant base for MediaService
open class MediaServiceServant: NPRPCServant, MediaServiceProtocol, @unchecked Sendable {
  public override init() { super.init() }

  public override func getClass() -> String   {
    return "live_blog/live_blog.MediaService"
  }

  open func openPostVideo(post_id: UInt64) -> AsyncStream<binary>   {
    fatalError("Subclass must implement openPostVideo")
  }

  // Dispatch incoming RPC calls
  public override func dispatch(buffer: FlatBuffer, remoteEndpoint: NPRPCEndpoint)   {
    guard let data = buffer.data else { return }

    // Check message type to route streaming vs regular calls
    let msgId = data.load(fromByteOffset: MemoryLayout<NPRPC.impl.Header>.offset(of: \NPRPC.impl.Header.msg_id)!, as: Int32.self)

    if msgId == impl.MessageId.streamInitialization.rawValue     {
      let streamFuncIdx = data.load(fromByteOffset: (16 + MemoryLayout<NPRPC.impl.StreamInit>.offset(of: \NPRPC.impl.StreamInit.func_idx)!), as: UInt8.self)
      switch streamFuncIdx       {
        case 0: // OpenPostVideo
          // Streaming method dispatch
          guard let data = buffer.data else { return }
          let streamId = data.load(fromByteOffset: (16 + MemoryLayout<NPRPC.impl.StreamInit>.offset(of: \NPRPC.impl.StreamInit.stream_id)!), as: UInt64.self)

          // Unmarshal input arguments
          let ia = unmarshal_live_blog_M11(buffer: data, offset: 48)

          // Get stream_manager for streaming (heap-allocated, survives after dispatch returns)
          guard let sessionCtx = self.sessionContext,
                let streamManager = nprpc_get_stream_manager(sessionCtx) else {
            makeSimpleAnswer(buffer: buffer, messageId: impl.MessageId.error_BadInput)
            return
          }
          let writer = NPRPC.createStreamManagerWriter(streamManager: streamManager, streamId: streamId, initialPayloadCapacity: 128, serializer: { (buffer: FlatBuffer, offset: Int, value: [UInt8]) in NPRPC.marshal_stream_fundamental_vector(buffer: buffer, offset: offset, value: value) })
          let source = openPostVideo(post_id: ia._1)
          makeSimpleAnswer(buffer: buffer, messageId: impl.MessageId.success)
          Task {
            for await value in source {
              writer.write(value)
            }
            writer.close()
          }

        default:
          makeSimpleAnswer(buffer: buffer, messageId: impl.MessageId.error_UnknownFunctionIdx)
      } // switch streamFuncIdx
      return
    }

    // Read function index from CallHeader
    let functionIdx = data.load(fromByteOffset: (16 + MemoryLayout<NPRPC.impl.CallHeader>.offset(of: \NPRPC.impl.CallHeader.function_idx)!), as: UInt8.self)

    switch functionIdx     {
      default:
        makeSimpleAnswer(buffer: buffer, messageId: impl.MessageId.error_UnknownFunctionIdx)
    } // switch
  } // dispatch
}

