// Generated by npidl compiler
// DO NOT EDIT - all changes will be lost

import NPRPC

public typealias binary = [UInt8]
public enum PresenceEventKind: Int32, Codable, Sendable {
  case joined
  case left
  case typing
}

public struct AuthorPreview: Codable, Sendable {
  public var id: UInt64 = 0
  public var slug: String = ""
  public var name: String = ""
  public var bio: String = ""
  public var avatar_url: String = ""

  public init() {}

  public init(id: UInt64, slug: String, name: String, bio: String, avatar_url: String)   {
    self.id = id
    self.slug = slug
    self.name = name
    self.bio = bio
    self.avatar_url = avatar_url
  }
}


// MARK: - Marshal AuthorPreview
public func marshal_AuthorPreview(buffer: FlatBuffer, offset: Int, data: AuthorPreview) {
  guard let buf = buffer.data else { return }
  buf.storeBytes(of: data.id, toByteOffset: offset + 0, as: UInt64.self)
  NPRPC.marshal_string(buffer: buffer, offset: offset + 8, string: data.slug)
  NPRPC.marshal_string(buffer: buffer, offset: offset + 16, string: data.name)
  NPRPC.marshal_string(buffer: buffer, offset: offset + 24, string: data.bio)
  NPRPC.marshal_string(buffer: buffer, offset: offset + 32, string: data.avatar_url)
}

// MARK: - Unmarshal AuthorPreview
public func unmarshal_AuthorPreview(buffer: UnsafeRawPointer, offset: Int) -> AuthorPreview {
  var result = AuthorPreview()
  result.id = buffer.load(fromByteOffset: offset + 0, as: UInt64.self)
  result.slug = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 8)
  result.name = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 16)
  result.bio = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 24)
  result.avatar_url = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 32)
  return result
}

public struct PostPreview: Codable, Sendable {
  public var id: UInt64 = 0
  public var slug: String = ""
  public var title: String = ""
  public var excerpt: String = ""
  public var published_at: String = ""
  public var cover_url: String? = nil
  public var author: AuthorPreview = AuthorPreview()

  public init() {}

  public init(id: UInt64, slug: String, title: String, excerpt: String, published_at: String, cover_url: String?, author: AuthorPreview)   {
    self.id = id
    self.slug = slug
    self.title = title
    self.excerpt = excerpt
    self.published_at = published_at
    self.cover_url = cover_url
    self.author = author
  }
}


// MARK: - Marshal PostPreview
public func marshal_PostPreview(buffer: FlatBuffer, offset: Int, data: PostPreview) {
  guard let buf = buffer.data else { return }
  buf.storeBytes(of: data.id, toByteOffset: offset + 0, as: UInt64.self)
  NPRPC.marshal_string(buffer: buffer, offset: offset + 8, string: data.slug)
  NPRPC.marshal_string(buffer: buffer, offset: offset + 16, string: data.title)
  NPRPC.marshal_string(buffer: buffer, offset: offset + 24, string: data.excerpt)
  NPRPC.marshal_string(buffer: buffer, offset: offset + 32, string: data.published_at)
  if let value = data.cover_url {
    NPRPC.marshal_optional_struct(buffer: buffer, offset: offset + 40, value: value) { buf, off in
      NPRPC.marshal_string(buffer: buf, offset: off, string: value)
    }
  } else {
    buf.storeBytes(of: UInt32(0), toByteOffset: offset + 40, as: UInt32.self)
  }
  marshal_AuthorPreview(buffer: buffer, offset: offset + 48, data: data.author)
}

// MARK: - Unmarshal PostPreview
public func unmarshal_PostPreview(buffer: UnsafeRawPointer, offset: Int) -> PostPreview {
  var result = PostPreview()
  result.id = buffer.load(fromByteOffset: offset + 0, as: UInt64.self)
  result.slug = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 8)
  result.title = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 16)
  result.excerpt = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 24)
  result.published_at = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 32)
  if buffer.load(fromByteOffset: offset + 40, as: UInt32.self) != 0 {
    result.cover_url = NPRPC.unmarshal_optional_struct(buffer: buffer, offset: offset + 40) { buf, off in
      NPRPC.unmarshal_string(buffer: buf, offset: off)
    }
  } else {
    result.cover_url = nil
  }
  result.author = unmarshal_AuthorPreview(buffer: buffer, offset: offset + 48)
  return result
}

public struct PostPage: Codable, Sendable {
  public var page: UInt32 = 0
  public var page_size: UInt32 = 0
  public var total_posts: UInt32 = 0
  public var posts: [PostPreview] = []

  public init() {}

  public init(page: UInt32, page_size: UInt32, total_posts: UInt32, posts: [PostPreview])   {
    self.page = page
    self.page_size = page_size
    self.total_posts = total_posts
    self.posts = posts
  }
}


// MARK: - Marshal PostPage
public func marshal_PostPage(buffer: FlatBuffer, offset: Int, data: PostPage) {
  guard let buf = buffer.data else { return }
  buf.storeBytes(of: data.page, toByteOffset: offset + 0, as: UInt32.self)
  buf.storeBytes(of: data.page_size, toByteOffset: offset + 4, as: UInt32.self)
  buf.storeBytes(of: data.total_posts, toByteOffset: offset + 8, as: UInt32.self)
  NPRPC.marshal_struct_vector(buffer: buffer, offset: offset + 12, vector: data.posts, elementSize: 88, elementAlignment: 8) { buf, off, elem in
    marshal_PostPreview(buffer: buf, offset: off, data: elem)
  }
}

// MARK: - Unmarshal PostPage
public func unmarshal_PostPage(buffer: UnsafeRawPointer, offset: Int) -> PostPage {
  var result = PostPage()
  result.page = buffer.load(fromByteOffset: offset + 0, as: UInt32.self)
  result.page_size = buffer.load(fromByteOffset: offset + 4, as: UInt32.self)
  result.total_posts = buffer.load(fromByteOffset: offset + 8, as: UInt32.self)
  result.posts = NPRPC.unmarshal_struct_vector(buffer: buffer, offset: offset + 12, elementSize: 88) { buf, off in
    unmarshal_PostPreview(buffer: buf, offset: off)
  }
  return result
}

public struct PostDetail: Codable, Sendable {
  public var id: UInt64 = 0
  public var slug: String = ""
  public var title: String = ""
  public var summary: String = ""
  public var body_html: String = ""
  public var published_at: String = ""
  public var author: AuthorPreview = AuthorPreview()
  public var tags1111: UInt8 = 0

  public init() {}

  public init(id: UInt64, slug: String, title: String, summary: String, body_html: String, published_at: String, author: AuthorPreview, tags1111: UInt8)   {
    self.id = id
    self.slug = slug
    self.title = title
    self.summary = summary
    self.body_html = body_html
    self.published_at = published_at
    self.author = author
    self.tags1111 = tags1111
  }
}


// MARK: - Marshal PostDetail
public func marshal_PostDetail(buffer: FlatBuffer, offset: Int, data: PostDetail) {
  guard let buf = buffer.data else { return }
  buf.storeBytes(of: data.id, toByteOffset: offset + 0, as: UInt64.self)
  NPRPC.marshal_string(buffer: buffer, offset: offset + 8, string: data.slug)
  NPRPC.marshal_string(buffer: buffer, offset: offset + 16, string: data.title)
  NPRPC.marshal_string(buffer: buffer, offset: offset + 24, string: data.summary)
  NPRPC.marshal_string(buffer: buffer, offset: offset + 32, string: data.body_html)
  NPRPC.marshal_string(buffer: buffer, offset: offset + 40, string: data.published_at)
  marshal_AuthorPreview(buffer: buffer, offset: offset + 48, data: data.author)
  buf.storeBytes(of: data.tags1111, toByteOffset: offset + 88, as: UInt8.self)
}

// MARK: - Unmarshal PostDetail
public func unmarshal_PostDetail(buffer: UnsafeRawPointer, offset: Int) -> PostDetail {
  var result = PostDetail()
  result.id = buffer.load(fromByteOffset: offset + 0, as: UInt64.self)
  result.slug = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 8)
  result.title = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 16)
  result.summary = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 24)
  result.body_html = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 32)
  result.published_at = NPRPC.unmarshal_string(buffer: buffer, offset: offset + 40)
  result.author = unmarshal_AuthorPreview(buffer: buffer, offset: offset + 48)
  result.tags1111 = buffer.load(fromByteOffset: offset + 88, as: UInt8.self)
  return result
}

