// Copyright (c) 2021-2025, Nikita Pennie <nikitapnn1@gmail.com>
// SPDX-License-Identifier: MIT

#pragma once

// Shared default values for NPRPC configuration structures.
// Keep these macros in sync across the core C++ API and the Swift bridge.

#define NPRPC_DEFAULT_LOG_LEVEL_U32 3
#define NPRPC_DEFAULT_HTTP_MAX_REQUEST_BODY_SIZE 10'000
#define NPRPC_DEFAULT_HTTP_WEBSOCKET_COMPRESSION_ENABLED true
#define NPRPC_DEFAULT_HTTP_WEBSOCKET_MAX_MESSAGE_SIZE (2 * 1024 * 1024)
#define NPRPC_DEFAULT_HTTP_WEBTRANSPORT_MAX_MESSAGE_SIZE (2 * 1024 * 1024)
#define NPRPC_DEFAULT_HTTP_WEBSOCKET_MAX_ACTIVE_SESSIONS_PER_IP 0
#define NPRPC_DEFAULT_HTTP_WEBSOCKET_UPGRADES_PER_IP_PER_SECOND 0
#define NPRPC_DEFAULT_HTTP_WEBSOCKET_UPGRADES_BURST 0
#define NPRPC_DEFAULT_HTTP_WEBSOCKET_REQUESTS_PER_SESSION_PER_SECOND 0
#define NPRPC_DEFAULT_HTTP_WEBSOCKET_REQUESTS_BURST 0
#define NPRPC_DEFAULT_HTTP3_WORKER_COUNT 4
#define NPRPC_DEFAULT_HTTP3_MAX_ACTIVE_CONNECTIONS_PER_IP 0
#define NPRPC_DEFAULT_HTTP3_MAX_NEW_CONNECTIONS_PER_IP_PER_SECOND 0
#define NPRPC_DEFAULT_HTTP3_MAX_NEW_CONNECTIONS_BURST 0
#define NPRPC_DEFAULT_HTTP_RPC_MAX_REQUESTS_PER_IP_PER_SECOND 0
#define NPRPC_DEFAULT_HTTP_RPC_MAX_REQUESTS_BURST 0
#define NPRPC_DEFAULT_HTTP_WEBTRANSPORT_CONNECTS_PER_IP_PER_SECOND 0
#define NPRPC_DEFAULT_HTTP_WEBTRANSPORT_CONNECTS_BURST 0
#define NPRPC_DEFAULT_HTTP_WEBTRANSPORT_REQUESTS_PER_SESSION_PER_SECOND 0
#define NPRPC_DEFAULT_HTTP_WEBTRANSPORT_REQUESTS_BURST 0
#define NPRPC_DEFAULT_HTTP_WEBTRANSPORT_STREAM_OPENS_PER_SESSION_PER_SECOND 0
#define NPRPC_DEFAULT_HTTP_WEBTRANSPORT_STREAM_OPENS_BURST 0
#define NPRPC_DEFAULT_WATCH_FILES false
